WebUI/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;
using System.Data.SqlClient;
using System.Configuration;

namespace WebUI.Controllers
{
    /// <summary>
    /// Основной контроллер (в данном приложении — единственный).
    /// </summary>
    public class SurveyController : Controller
    {
        /// <summary>
        /// Метод по умолчанию (пустая страница анкеты).
        /// </summary>
        /// <returns>Страница с пустой анкетой</returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Метод для проверки отправляемых на сервер данных из анкеты.
        /// </summary>
        /// <returns>Результат проверки заполнения анкеты.</returns>
        public ActionResult FormHandler(SurveyPostParams parameters)
        {
            bool sexError = false;
            bool thingsError = false;
            if (!ModelState.IsValid)
            {
                sexError = true;
            }

            if (!parameters.HasFridge && !parameters.HasTV && !parameters.HasPC)
            {
                thingsError = true;
            }

            if (sexError || thingsError)
            {
                return Json(new { success = false, sexError, thingsError});
            }

            var conn = new SqlConnection(ConfigurationManager.ConnectionStrings["SurveyDBConnectionString"].ConnectionString);
            var cmd = new SqlCommand
            {
                CommandType = System.Data.CommandType.Text,
                CommandText = "INSERT INTO Answers (Sex, HasFridge, HasTV, HasPC) Values (@sex, @hasFridge, @hasTV, @hasPC)"
            };

            cmd.Parameters.AddWithValue("@sex", parameters.Sex);
            cmd.Parameters.AddWithValue("@hasFridge", parameters.HasFridge);
            cmd.Parameters.AddWithValue("@hasTV", parameters.HasTV);
            cmd.Parameters.AddWithValue("@hasPC", parameters.HasPC);
            cmd.Connection = conn;

            conn.Open();
            cmd.ExecuteNonQuery();
            conn.Close();

            return Json(new { success = true });
        }

        /// <summary>
        /// Метод для отображения страницы статистики.
        /// </summary>
        /// <returns>Страница статистики.</returns>
        public ActionResult Statistics()
        {
            var conn = new SqlConnection(ConfigurationManager.ConnectionStrings["SurveyDBConnectionString"].ConnectionString);
            var dataAdapter = new SqlDataAdapter("SELECT * FROM Answers", conn);
            var dataSet = new Answers();
            conn.Open();
            dataAdapter.Fill(dataSet, "Answers");
            conn.Close();

            int count = dataSet.Tables["Answers"].Rows.Count;
            ViewBag.MalePercentage = Math.Round((decimal)dataSet.Tables["Answers"].Select("Sex = true").Count() / count * 100);
            ViewBag.FemalePercentage = 100 - ViewBag.MalePercentage;
            ViewBag.HasFridgePercentage = Math.Round((decimal)dataSet.Tables["Answers"].Select("HasFridge = true").Count() / count * 100);
            ViewBag.HasTVPercentage = Math.Round((decimal)dataSet.Tables["Answers"].Select("HasTV = true").Count() / count * 100);
            ViewBag.HasPCPercentage = Math.Round((decimal)dataSet.Tables["Answers"].Select("HasPC = true").Count() / count * 100);

            return View();
        }
	}
}

WebUI/Views/Survey/Index.cshtml
@{
    ViewBag.Title = "Опрос";
}

<div class="panel panel-success">
    <div class="panel-heading text-center"><h3>Заполните, пожалуйста, анкету</h3></div>
    <div class="panel-body text-center">
        @using (Html.BeginForm("FormHandler", "Survey", FormMethod.Post, new { id = "main" })) {
            <div>
                <span class="text-success h4">Укажите Ваш пол:</span>
                <br />
                <div id="sexError" class="text-danger" style="display: none">Не выбран пол!</div>
                <br />
                <div class="form-group">
                    @Html.RadioButton("sex", true, new { id = "male" })
                    @Html.Label("male", "Мужской")
                </div>
                <div class="form-group">
                    @Html.RadioButton("sex", false, new { id = "female" })
                    @Html.Label("female", "Женский")
                </div>
            </div>
            <div>
                <span class="text-success h4">Что из перечисленного у вас есть дома?</span>
                <br />
                <div id="thingsError" class="text-danger" style="display: none">Не выбраны имеющиеся дома предметы!</div>
                <br />
                <div class="form-group">
                    @Html.CheckBox("hasFridge")
                    @Html.Label("hasFridge", "Холодильник")
                </div>
                <div class="form-group">
                    @Html.CheckBox("hasTV")
                    @Html.Label("hasTV", "Телевизор")
                </div>
                <div class="form-group">
                    @Html.CheckBox("hasPC")
                    @Html.Label("hasPC", "Компьютер")
                </div>
            </div>
            <div class="text-center">
                <input id="okButton" class="btn btn-success btn-lg" type="button" value="Ответить">
            </div>
            <br />
            <div class="btn btn-info btn-xs text-center">
                @Html.ActionLink("Просмотр статистики", "Statistics")
            </div>
        }
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#okButton").click(function () {
            $.ajax({
                url: "/Survey/FormHandler",
                cache: false,
                type: "POST",
                dataType: "json",
                data: $("#main").serialize(),
                success: function (data) {
                    if (data.success) {
                        alert("Спасибо за участие в опросе!");
                        $('#main')[0].reset();
                        $('#sexError').hide();
                        $('#thingsError').hide();
                    } else {
                        if (data.sexError) {
                            $('#sexError').show();
                        }
                        if (data.thingsError) {
                            $('#thingsError').show();
                        }
                    }
                },
                error: function (data) {
                    alert("Не удалось сохранить данные!");
                }
            });
        });
    });
</script>

WebUI/Views/Survey/Statistics.cshtml
@{
    ViewBag.Title = "Статистика";
}

<div class="panel panel-success">
    <div class="panel-heading text-center"><h3>Статистика ответов на вопросы анкеты</h3></div>
    <div class="panel-body text-center">
        <div>
            <span class="text-success h3">Пол:</span>
            <br />
            <br />
            <span class="text-primary h4">Мужской: @ViewBag.MalePercentage %</span>
            <br />
            <span class="text-primary h4">Женский: @ViewBag.FemalePercentage %</span>
        </div>
        <br />
        <div>
            <span class="text-success h3">Наличие техники:</span>
            <br />
            <br />
            <span class="text-primary h4">Холодильник: @ViewBag.HasFridgePercentage %</span>
            <br />
            <span class="text-primary h4">Телевизор: @ViewBag.HasTVPercentage %</span>
            <br />
            <span class="text-primary h4">Компьютер: @ViewBag.HasPCPercentage %</span>
        </div>
        <br />
        <div class="btn btn-info btn-xs">
            @Html.ActionLink("Вернуться к анкетированию", "Index")
        </div>
    </div>
</div>